<%@ Page Title="" Language="C#" MasterPageFile="~/Prog5/Prog5MasterPage.master" AutoEventWireup="true" CodeBehind="Updating.aspx.cs" Inherits="WebSite.Prog5.Updating" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageContentPlaceHolder" runat="server">
    <table class="auto-style11">
        <tr>
            <td class="auto-style12">&nbsp;</td>
            <td class="auto-style4">
                <asp:DetailsView ID="DeVProduct" runat="server" AutoGenerateRows="False" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" DataKeyNames="ProductID" DataSourceID="SDSServer" ForeColor="Black" GridLines="None" Height="50px" Width="125px" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" CssClass="auto-style7" OnItemDeleted="DeVProduct_ItemDeleted" OnItemInserted="DeVProduct_ItemInserted" OnItemUpdated="DeVProduct_ItemUpdated">
                    <AlternatingRowStyle BackColor="PaleGoldenrod" />
                    <EditRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                    <Fields>
                        <asp:BoundField DataField="ProductID" HeaderText="ProductID" ReadOnly="True" SortExpression="ProductID" />
                        <asp:BoundField DataField="ProductName" HeaderText="ProductName" SortExpression="ProductName" />
                        <asp:BoundField DataField="UnitPrice" HeaderText="UnitPrice" SortExpression="UnitPrice" />
                        <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                    </Fields>
                    <FooterStyle BackColor="Tan" />
                    <HeaderStyle BackColor="Tan" Font-Bold="True" />
                    <PagerSettings Visible="False" />
                    <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
                </asp:DetailsView>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style13">
                <asp:Button ID="btnFirst" runat="server" Text="First" OnClick="btnFirst_Click" />
            </td>
            <td class="auto-style15">
                <asp:Button ID="btnPrevious" runat="server" Text="Previous" OnClick="btnPrevious_Click" />
                <asp:Button ID="btnNext" runat="server" Text="Next" CssClass="auto-style16" OnClick="btnNext_Click" />
            </td>
            <td class="auto-style13">
                <asp:Button ID="btnLast" runat="server" Text="Last" OnClick="btnLast_Click" />
            </td>
        </tr>
        <tr>
            <td class="auto-style12">&nbsp;</td>
            <td class="auto-style4">
                <asp:TextBox ID="txtMessage" runat="server" ReadOnly="True" TextMode="MultiLine"></asp:TextBox>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style12">&nbsp;</td>
            <td class="auto-style4">
                <asp:SqlDataSource ID="SDSServer" runat="server" ConnectionString="<%$ ConnectionStrings:UWPCS3870ConnectionStringServer %>" SelectCommand="SELECT * FROM [Product]" DeleteCommand="delete from Product where ProductID = @ProductID" InsertCommand="insert into Product(ProductID, ProductName, UnitPrice, Description) values (@ProductID, @ProductName, @UnitPrice, @Description)" UpdateCommand="update Product Set ProductName = @ProductName, UnitPrice = @UnitPrice, Description = @Description where ProductID = @ProductID">
                    <DeleteParameters>
                        <asp:Parameter Name="ProductID" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="ProductID" />
                        <asp:Parameter Name="ProductName" />
                        <asp:Parameter Name="UnitPrice" />
                        <asp:Parameter Name="Description" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="ProductName" />
                        <asp:Parameter Name="UnitPrice" />
                        <asp:Parameter Name="Description" />
                        <asp:Parameter Name="ProductID" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </td>
            <td>&nbsp;</td>
        </tr>
    </table>
</asp:Content>
